---
language: node_js
node_js: node

cache: yarn

env:
  global:
    - ULTIMANAGER_API_ROOT=http://ultimanager.example.com

script:
  - yarn prettier:check
  - yarn lint
  - yarn test
  - yarn build

after_success: yarn codecov

notifications:
  email:
    on_failure: always
    on_success: never
