---
env:
  global:
    - ULTIMANAGER_API_ROOT=http://localhost

matrix:
  include:
    - language: node_js
      node_js: node

      cache: yarn

      script:
        - yarn prettier:check
        - yarn lint
        - yarn test
        - yarn build

      after_success: yarn codecov

    # Test building the docker image
    - language: minimal

      services:
        - docker

      script:
        - docker build -t ultimanager-web .

notifications:
  email:
    on_failure: always
    on_success: never
